<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="guru_Default" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Guru Anubis</title>
</head>
<body style="font-family: sans-serif">
    <form id="form1" runat="server">
        <div>
            <strong>Como funciona o Guru Anubis?</strong><br />
            O <strong>Guru Anubis</strong> é um algoritimo open source criado para auxiliar as pessoas dentro do mundo das redes neurais, o <strong>Guru Anubis</strong> foi construído a partir da técnica de rede neural chamada Perceptron, e integrado dentro do mundo das criptomoedas, basicamente ele irá pegar os dados do passado do bitcoin ou outras criptomoedas e irá tentar prever o preço futuro, como o preço que o bitcoin provavelmente estará amanhã por exemplo, ele irá realizar o treinamento da sua rede neural e lhe dar um output de dado.<br />
        </div>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <strong>Vamos lá!</strong></p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            Informe por favor a quantidade de inputs que você quer no seu neurónio?(padrão 5, isso tem relação com o intervalo de tempo, 5 em 1d, significaria 5 dias por amostragem)</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <asp:TextBox ID="txtInput" runat="server">5</asp:TextBox>
        </p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            Qual output de saída do seu neurónio?(fixo 1, em breve teremos mais opçcões)</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <asp:TextBox ID="txtOutPut" runat="server" Enabled="False">1</asp:TextBox>
        </p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            Qual o intervalo de tempo que você quer consultar?(1d por padrão, mas você pode consultar 1h por exemplou ou 15m)</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <asp:TextBox ID="txtInterval" runat="server">1d</asp:TextBox>
        </p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            Quantas epócas você quer realizar o seu treinamento da sua rede neural?(padrão e máximo 99999)</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <asp:TextBox ID="txtEpoch" runat="server">99999</asp:TextBox>
        </p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            Qual moeda você quer realizar o estudo?(padrão BTCUSDT em breve teremos mais)</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <asp:TextBox ID="txtPair" runat="server" Enabled="False">BTCUSDT</asp:TextBox>
        </p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Treinar a rede e informar resultado!" />
&nbsp;<strong>(Atenção, isso pode levar alguns momentos!)</strong></p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <asp:Label ID="lblResultado" runat="server" style="font-weight: 700; font-size: x-large;" ForeColor="#0000CC"></asp:Label>
        </p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <br />
        <strong>Qual a definiçcão de Perceptron?</strong><br />
        <span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">O<span>&nbsp;</span></span><b style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">perceptron</b><span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span>&nbsp;</span>é 
        um tipo de<span>&nbsp;</span></span><a href="https://pt.wikipedia.org/wiki/Rede_neural_artificial" style="text-decoration: none; color: rgb(11, 0, 128); background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Rede neural artificial">rede neural artificial</a><span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span>&nbsp;</span>inventada 
        em 1957 por Frank Rosenblatt no<span>&nbsp;</span></span><a class="new" href="https://pt.wikipedia.org/w/index.php?title=Cornell_Aeronautical_Laboratory&amp;action=edit&amp;redlink=1" style="text-decoration: none; color: rgb(165, 88, 88); background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Cornell Aeronautical Laboratory (página não existe)">Cornell Aeronautical Laboratory</a><span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">. 
        Ele pode ser visto como o tipo mais simples de<span>&nbsp;</span></span><a class="new" href="https://pt.wikipedia.org/w/index.php?title=Rede_neural_feedforward&amp;action=edit&amp;redlink=1" style="text-decoration: none; color: rgb(165, 88, 88); background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Rede neural feedforward (página não existe)">rede neural feedforward</a><span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">: 
        um<span>&nbsp;</span></span><a class="new" href="https://pt.wikipedia.org/w/index.php?title=Classificador_linear&amp;action=edit&amp;redlink=1" style="text-decoration: none; color: rgb(165, 88, 88); background: none rgb(255, 255, 255); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;" title="Classificador linear (página não existe)">classificador linear</a><span style="color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">.</span><p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            O perceptron é um classificador binário que mapeia sua entrada<span>&nbsp;</span><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none; clip: rect(1px, 1px, 1px, 1px); overflow: hidden; position: absolute; width: 1px; height: 1px; opacity: 0; font-size: 16.52px;">
            <math alttext="{\displaystyle x}" xmlns="http://www.w3.org/1998/Math/MathML">
                <semantics><annotation encoding="application/x-tex"></annotation></semantics>
            </math>
            </span>
            <img alt="x" aria-hidden="true" class="mwe-math-fallback-image-inline" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/87f9e315fd7e2ba406057a97300593c4802b53e4" style="border: 0px; vertical-align: -0.338ex; margin: 0px; display: inline-block; width: 1.33ex; height: 1.676ex;" /></span><span>&nbsp;</span>(um<span>&nbsp;</span><a class="mw-disambig" href="https://pt.wikipedia.org/wiki/Vetor" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Vetor">vetor</a><span>&nbsp;</span>de valor real) para um valor de saída<span>&nbsp;</span><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none; clip: rect(1px, 1px, 1px, 1px); overflow: hidden; position: absolute; width: 1px; height: 1px; opacity: 0; font-size: 16.52px;">
            <math alttext="{\displaystyle f(x)}" xmlns="http://www.w3.org/1998/Math/MathML">
                <semantics><annotation encoding="application/x-tex"></annotation></semantics>
            </math>
            </span>
            <img alt="f(x)" aria-hidden="true" class="mwe-math-fallback-image-inline" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/202945cce41ecebb6f643f31d119c514bec7a074" style="border: 0px; vertical-align: -0.838ex; margin: 0px; display: inline-block; width: 4.418ex; height: 2.843ex;" /></span><span>&nbsp;</span>(uma valor binário simples) através da matriz.</p>
        <dl style="margin-top: 0.2em; margin-bottom: 0.5em; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            <dd style="margin-left: 1.6em; margin-bottom: 0.1em; margin-right: 0px;"><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none; clip: rect(1px, 1px, 1px, 1px); overflow: hidden; position: absolute; width: 1px; height: 1px; opacity: 0; font-size: 16.52px;">
                <math alttext="{\displaystyle f(x)={\begin{cases}1&amp;{\text{if }}w\cdot x+b\geq 0\\0&amp;{\text{else}}\end{cases}}}" xmlns="http://www.w3.org/1998/Math/MathML">
                    <semantics><annotation encoding="application/x-tex"></annotation></semantics>
                </math>
                </span>
                <img alt="{\displaystyle f(x)={\begin{cases}1&amp;{\text{if }}w\cdot x+b\geq 0\\0&amp;{\text{else}}\end{cases}}}" aria-hidden="true" class="mwe-math-fallback-image-inline" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/1ad189bf14dcacf95352d9e32f708b278e49bace" style="border: 0px; vertical-align: -2.505ex; display: inline-block; width: 28.207ex; height: 6.176ex;" /></span></dd>
        </dl>
        <p style="margin: 0.5em 0px; line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">
            Onde<span>&nbsp;</span><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none; clip: rect(1px, 1px, 1px, 1px); overflow: hidden; position: absolute; width: 1px; height: 1px; opacity: 0; font-size: 16.52px;">
            <math alttext="{\displaystyle w}" xmlns="http://www.w3.org/1998/Math/MathML">
                <semantics><annotation encoding="application/x-tex"></annotation></semantics>
            </math>
            </span>
            <img alt="w" aria-hidden="true" class="mwe-math-fallback-image-inline" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/88b1e0c8e1be5ebe69d18a8010676fa42d7961e6" style="border: 0px; vertical-align: -0.338ex; margin: 0px; display: inline-block; width: 1.664ex; height: 1.676ex;" /></span><span>&nbsp;</span>é um vetor de peso real e<span>&nbsp;</span><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none; clip: rect(1px, 1px, 1px, 1px); overflow: hidden; position: absolute; width: 1px; height: 1px; opacity: 0; font-size: 16.52px;">
            <math alttext="{\displaystyle w\cdot x}" xmlns="http://www.w3.org/1998/Math/MathML">
                <semantics><annotation encoding="application/x-tex"></annotation></semantics>
            </math>
            </span>
            <img alt="{\displaystyle w\cdot x}" aria-hidden="true" class="mwe-math-fallback-image-inline" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/69b9832ae727dd93d743ed1daf1f7940ebc16f43" style="border: 0px; vertical-align: -0.338ex; margin: 0px; display: inline-block; width: 4.673ex; height: 1.676ex;" /></span><span>&nbsp;</span>é o<span>&nbsp;</span><a href="https://pt.wikipedia.org/wiki/Produto_escalar" style="text-decoration: none; color: rgb(11, 0, 128); background: none;" title="Produto escalar">produto escalar</a><span>&nbsp;</span>(que computa uma soma com pesos) e<span>&nbsp;</span><span class="mwe-math-element"><span class="mwe-math-mathml-inline mwe-math-mathml-a11y" style="display: none; clip: rect(1px, 1px, 1px, 1px); overflow: hidden; position: absolute; width: 1px; height: 1px; opacity: 0; font-size: 16.52px;">
            <math alttext="{\displaystyle b}" xmlns="http://www.w3.org/1998/Math/MathML">
                <semantics><annotation encoding="application/x-tex"></annotation></semantics>
            </math>
            </span>
            <img alt="b" aria-hidden="true" class="mwe-math-fallback-image-inline" src="https://wikimedia.org/api/rest_v1/media/math/render/svg/f11423fbb2e967f986e36804a8ae4271734917c3" style="border: 0px; vertical-align: -0.338ex; margin: 0px; display: inline-block; width: 0.998ex; height: 2.176ex;" /></span><span>&nbsp;</span>é o viés (do inglês &quot;<i>bias</i>&quot;), um termo constante que não depende de qualquer valor de entrada.</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <img alt="Resultado de imagem para perceptron desenho" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN3c5t2c3Q8QQNjxCqrPlvXhqYgyG4HR46Nd20ZdLpCE9t1-qG" /></p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
           <a href="https://github.com/matheusgrijo/guruanubis"> O código fonte desta página está no GITHUB!</a></p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            &nbsp;</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            Considere fazer um DONATE para o projeto:</p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <span style="color: rgb(100, 100, 100); font-family: Poppins, sans-serif; font-size: 12.8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">BTC:<span>&nbsp;</span></span><b style="color: rgb(100, 100, 100); box-sizing: border-box; font-weight: bolder; font-family: Poppins, sans-serif; font-size: 12.8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">33foqEfvx3nMMVTP6bbXvBLxVFYHVkFw8V</b></p>
        <p style="line-height: inherit; color: rgb(34, 34, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 0.5em 0px; background-color: rgb(255, 255, 255)">
            <img src="https://chart.googleapis.com/chart?chs=250x250&amp;cht=qr&amp;chl=bitcoin:33foqEfvx3nMMVTP6bbXvBLxVFYHVkFw8V" /></p>
    </form>
</body>
</html>
